# Generated by Django 5.0.4 on 2026-03-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="lazuli_orde_status_291e3e_idx",
            old_name="lazuli_orde_status_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="lazuli_orde_created_3856d2_idx",
            old_name="lazuli_orde_created_idx",
        ),
    ]
