# Generated by Django 5.0.4 on 2026-03-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="lazuli_prod_categor_1c92e1_idx",
            old_name="lazuli_prod_categor_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="lazuli_prod_badge_660eca_idx",
            old_name="lazuli_prod_badge_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="lazuli_prod_created_047f42_idx",
            old_name="lazuli_prod_created_idx",
        ),
    ]
